### ISSUE TITLE
estimate dose control parameters

### ISSUE THREAD

**Issue by vjd** [PumasAI/Pumas.jl#649] opened 2019-08-28 13:13 UTC
I will post a reproducible example soon once some of the PR's are merged

**Comment by andreasnoack** [comment] 2019-09-02 11:06
On master, I'm getting
````
julia> o = fit(iv,data,param,Pumas.FOCEI())
FittedPumasModel

Successful minimization:                true

Likelihood approximation:        Pumas.FOCEI
Objective function value:            14.3725
Total number of observation records:     288
Number of active observation records:    288
Number of subjects:                       24

----------------------
           Estimate
----------------------
tvcl       11.065
tvv        49.12
dur         1.0032
Ω₁,₁        0.046427
Ω₂,₂        0.056934
σ_prop      0.0010331
----------------------
```
so has this been fixed?

**Comment by pkofod** [comment] 2019-09-02 11:09
Any chance it's because something was incorrectly handled in the dataframe construction, that was fixed here ? https://github.com/PumasAI/Pumas.jl/pull/489

**Comment by ChrisRackauckas** [comment] 2019-09-02 11:11
Quite possibly. We should still get this added as a test.

**Comment by andreasnoack** [comment] 2019-09-02 11:24
> Any chance it's because something was incorrectly handled in the dataframe construction, that was fixed here ? #489

Doesn't seem to be it. I can estimate `dur` even in Pumas 0.2. The variance is just tiny so sometimes the show method rounds to `1.0`.

**Comment by ChrisRackauckas** [comment] 2019-09-02 11:27
Try fitting with a different initial from the true value? I would assume the gradient is still weird due to the lack of time duals.

**Comment by andreasnoack** [comment] 2019-09-02 11:28
We tried starting it in 3.0 and it still found the ~1.0 solution.

**Comment by ChrisRackauckas** [comment] 2019-09-02 11:29
Try having a bioav as well? We should make a test that just really loads up on the DCPs.

**Comment by ChrisRackauckas** [comment] 2019-09-02 11:30
This could be another example of an AD bug accidentally fixed by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/841

**Comment by andreasnoack** [comment] 2019-09-02 11:49
Same with OrdinaryDiffEq@5.12.0. Notice that it's not clear from the original post that there is an issue.

**Comment by ChrisRackauckas** [comment] 2019-09-02 11:50
indeed. Try other dcps

**Comment by pkofod** [comment] 2019-09-02 12:57
> indeed. Try other dcps

But do we know that there was ever a problem? From what we see, it seems that @vjd was just tricked by the fact that the parameter estimate ends up being `1.0`, but if you try to simulate and fit different models, it always fits the `dur` very well. So is there a problem, or did it just appear as if there was? Even generating one model and simulating with one named tuple param and then taking that data set and fitting it with a newly compile model with different parameters correct estimates the `dur` in all cases I've tried.

**Comment by ChrisRackauckas** [comment] 2019-09-02 13:47
There was a problem like a year ago. We need tests on this anyways, so whoever has an open computer might as well put a test in for it.

**Comment by pkofod** [comment] 2019-09-03 11:23
Okay, so I tried a few things here. @vjd  seemed to indicate on the call that this was with an ode. I tried reformulating the model as
```

iv_ode = @model begin
  @param   begin
    tvcl ∈ RealDomain(lower=0)
    tvv ∈ RealDomain(lower=0)
    dur ∈ RealDomain(lower=0)
    Ω ∈ PDiagDomain(2)
    σ_prop ∈ RealDomain(lower=0)
  end

  @random begin
    η ~ MvNormal(Ω)
  end

  @pre begin
    CL = tvcl * (Wt/70)^0.75 * exp(η[1])
    V  = tvv * (Wt/70) * exp(η[2])
    duration = (Central = dur,)
  end

  @covariates Wt

  @dynamics begin
     Central' = -(CL/V)*Central
  end

  @derived begin
      cp := @. (Central / V)
      dv ~ @. Normal(cp, sqrt(cp^2*σ_prop))
    end
end
```
is this correct? If I fit with that, I do indeed get a promotion problem, but it doesn't show up as a non-changing parameter. Rather, it shows up as a hard error in `perform_step` (`[...]/src/perform_step/low_order_rk_perform_step.jl:599`), see https://gist.github.com/pkofod/5e39d37a1d764bc2f8bc6648e6cdbb91 (warning, loooooots if type info in that one.)

On the other hand, going back to the model as shown in OP. Let's draw the sum of marginal likelihood as a function of dur only.
```
julia> f(dur) = sum(Pumas.marginal_nll(iv, sub, (
         tvcl = o.param.tvcl,
         tvv  = o.param.tvv,
         dur = dur,
         Ω = o.param.Ω,
         σ_prop = o.param.σ_prop
         )
       , vrandeffs, Pumas.FOCEI()) for (sub, vrandeffs) in zip(data, o.vvrandeffs))
f (generic function with 1 method)

julia> xx = range(0.1,2; length=100)
0.1:0.01919191919191919:2.0

julia> plot(xx, f.(xx), xlabel="tvv", ylabel="cost", legend=false)
```
We get 



So yeah, I think there's a promotion issue in the numerical ode version as Chris already said, but that can't have explained @vjd's original problem, since that won't even got through. So honestly, I think it's just the fact that a) the printed parameter is 1.0 and b) the duration seems to be extremely well-identified.

**Comment by ChrisRackauckas** [comment] 2019-09-03 11:26
>is this correct? If I fit with that, I do indeed get a promotion problem, but it doesn't show up as a non-changing parameter. Rather, it shows up as a hard error in perform_step ([...]/src/perform_step/low_order_rk_perform_step.jl:599), see https://gist.github.com/pkofod/5e39d37a1d764bc2f8bc6648e6cdbb91 (warning, loooooots if type info in that one.)

Yes, this is the error I was mentioning about time needing to be Dual typed. I might get to that today if someone can try and reproduce https://github.com/PumasAI/Pumas.jl/pull/653 locally.

**Comment by pkofod** [comment] 2019-09-03 11:43
>  I might get to that today if someone can try and reproduce #653 locally.

I'm running the tests now

**Comment by pkofod** [comment] 2019-10-04 19:26
Just putting this here as a note: To estimate lag parameters time needs to be dual.

**Closed** 2020-02-10 19:03 UTC
