### ISSUE TITLE
Population to take number of subjects as kwargs

### ISSUE THREAD

**Issue by vjd** [PumasAI/Pumas.jl#368] opened 2019-03-23 10:33 UTC
The `Population` function should allow a kwarg called `nids` or `nsubs` such that given a dose regimen e.g. `ev = DosageRegimen(100,cmt=1,addl=3)`, users should be able to pass the kwarg to generate a population. 

The current workflow is the following

1. Create a dosage regimen
```
ev = DosageRegimen(100, ii=24, addl=3)
```
2. Create a covariate generation function
```
choose_covariates() = (isPM = rand(["yes", "no"]),
                    Wt = rand(55:80))
```
3. If we want a single subject then we do 

```
s1 = Subject(id=1,evs=ev,cvs=(isPM="yes", Wt=70))
```
4. if we want a population of subjects, we do 

```
pop = Population(map(i -> Subject(id=i,evs=events,cvs=choose_covariates()),1:nsubs))
```
where `nsubs` is th number of subjects

Suggest dispatching `Population` to allow something like

```
pop = Population(nids,evs=ev,cvs=choose_covariates())
```
OR create a new function to generate population like below

```
function generate_population(events,nsubs=24)
  pop = Population(map(i -> Subject(id=i,evs=events,cvs=choose_covariates()),1:nsubs))
  return pop
end
```

Since `Population` collects `Subjects` together, maybe a dispatch as suggested above may not work, so perhaps creating a new function is better?

**Comment by pkofod** [comment] 2019-08-29 12:20
I think array comprehensions are simple enough that we don't need a separate function for this.

**Comment by vjd** [comment] 2019-08-29 13:06
I end up using this piece of code in almost every simulation that I do. So, thought it would be easy to have a generic function. But I agree. Tutorials on this would be easy

```
pop =  Population(map(i -> Subject(id=i, evs=sd, cvs = (Wt = choose_covariates(),)),1:24)) 
```

**Comment by ChrisRackauckas** [comment] 2019-08-29 13:16
I think that code is fine. The issue is that syntactically it's not easier than what we'd end up with, it's an extra unnecessary function, and then everyone will want options that make it harder to use than just writing the comprehension. This is the "too far" kind of tidyverse or Pandas function that IMO causes teaching and maitanance issues down the line, so I am going to close this.

**Closed by ChrisRackauckas** 2019-08-29 13:16 UTC
Labels: enhancement, golive
